print('Hickory Dickory Dock!\nThe mouse ran up the clock')
print()
print()
firstName=input("What is your name?")
print()
print(firstName.capitalize()+" "+"What a lovely name!")
print()
print(firstName.capitalize()+ ", How are you doing?\nMay I have your Last Name too?")
print()
lastName=input("Your Last Name please ")
print("Thank You")
print()
print(firstName.capitalize()+" "+lastName.capitalize()+", ""Nice to see you")